//
//  weatherPresenter.swift
//  TaskSix
//
//  Created by AllSpark on 04/12/19.
//  Copyright (c) 2019 AllSpark. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol weatherPresentationLogic
{
  func presentSomething(response: weather.Something.Response)
}

class weatherPresenter: weatherPresentationLogic
{
  weak var viewController: weatherDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: weather.Something.Response)
  {
    let viewModel = weather.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
