//
//  weatherInteractor.swift
//  TaskSix
//
//  Created by AllSpark on 04/12/19.
//  Copyright (c) 2019 AllSpark. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol weatherBusinessLogic
{
  func doSomething(request: weather.Something.Request)
}

protocol weatherDataStore
{
  //var name: String { get set }
}

class weatherInteractor: weatherBusinessLogic, weatherDataStore
{
  var presenter: weatherPresentationLogic?
  var worker: weatherWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: weather.Something.Request)
  {
    worker = weatherWorker()
    worker?.doSomeWork()
    
    let response = weather.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
