//
//  weatherRouter.swift
//  TaskSix
//
//  Created by AllSpark on 04/12/19.
//  Copyright (c) 2019 AllSpark. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol weatherRoutingLogic
{
  //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol weatherDataPassing
{
  var dataStore: weatherDataStore? { get }
}

class weatherRouter: NSObject, weatherRoutingLogic, weatherDataPassing
{
  weak var viewController: weatherViewController?
  var dataStore: weatherDataStore?
  
  // MARK: Routing
  
  //func routeToSomewhere(segue: UIStoryboardSegue?)
  //{
  //  if let segue = segue {
  //    let destinationVC = segue.destination as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //  } else {
  //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
  //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //    navigateToSomewhere(source: viewController!, destination: destinationVC)
  //  }
  //}

  // MARK: Navigation
  
  //func navigateToSomewhere(source: weatherViewController, destination: SomewhereViewController)
  //{
  //  source.show(destination, sender: nil)
  //}
  
  // MARK: Passing data
  
  //func passDataToSomewhere(source: weatherDataStore, destination: inout SomewhereDataStore)
  //{
  //  destination.name = source.name
  //}
}
